/**
 * Auto-generated plugin README content
 * Generated by scripts/generate-plugin-readmes.ts
 * DO NOT EDIT MANUALLY
 *
 * README Hash: 279fa6789dc7daa2ca6076dbec1b1fbfa4f6f0b52a1f2074e99609ace509c7fb
 */

export const pluginReadmes = {
  "fact-checker": "# Fact Checker\n\nAn agent that identifies and verifies factual claims in documents, checking them against current knowledge and reliable sources. Provides detailed verdicts on claim accuracy with evidence-based reasoning.\n\n## Configuration\n\n**Processing Limits:**\n- Maximum facts to process: **30**\n- Maximum claims per chunk: **20**\n\n**Quality Thresholds:**\n- Minimum quality threshold: **25**\n\n**Importance Scoring:**\n- High importance: **60+**\n- Medium importance: **40+**\n\n**Checkability Scoring:**\n- High checkability: **50+**\n\n**Truth Probability Ranges:**\n- High: **90+**\n- Medium: **70-90**\n- Low: **50-70**\n- Very Low: **≤40**\n- Likely False: **≤30**\n\n## How It Works\n\nThe agent processes documents by:\n1. Extracting factual claims and statements\n2. Categorizing claims by type (statistical, historical, scientific, etc.)\n3. Verifying each claim against current knowledge\n4. Providing verdicts with supporting evidence\n5. Suggesting corrections for inaccurate claims\n\n## Verification Categories\n\n- **Factual claims**: General statements about events, people, or things\n- **Statistical data**: Numbers, percentages, measurements, trends\n- **Historical facts**: Dates, events, historical figures and contexts\n- **Scientific facts**: Research findings, natural phenomena, technical data\n- **Geographic facts**: Locations, distances, demographic information\n- **Current events**: Recent developments, ongoing situations\n\n## Verdict Types\n\n- **True**: Claim is accurate and well-supported\n- **False**: Claim is demonstrably incorrect\n- **Partially True**: Contains accurate elements but is misleading or incomplete\n- **Outdated**: Was true but no longer current\n- **Unverifiable**: Cannot be verified with available information\n- **Misleading**: Technically true but presented in a deceptive way\n\n---\n*This documentation is programmatically generated from source code. Do not edit manually.*\n"
} as const;

export type PluginId = keyof typeof pluginReadmes;

export function getPluginReadme(pluginId: string): string {
  const typedPluginId = pluginId as PluginId;
  return pluginReadmes[typedPluginId] || `# ${pluginId}\n\n*README content not available*`;
}
