#!/usr/bin/env tsx

/**
 * Build script to generate plugin README files from source code
 * This ensures documentation stays synchronized with plugin configuration
 *
 * Generates TWO outputs:
 * 1. Markdown files for human reading (in internal-packages/db/system-agents/agents/readmes/)
 * 2. TypeScript module for runtime access (in internal-packages/db/system-agents/generated-plugin-readmes.ts)
 */

import fs from 'fs';
import path from 'path';
import { createHash } from 'crypto';

// Import readme generators from plugins
import { generateReadme as generateFactCheckReadme } from '../src/analysis-plugins/plugins/fact-check/readme-generator';
import { generateReadme as generateMathReadme } from '../src/analysis-plugins/plugins/math/readme-generator';
import { generateReadme as generateSpellingReadme } from '../src/analysis-plugins/plugins/spelling/readme-generator';
import { generateReadme as generateForecastReadme } from '../src/analysis-plugins/plugins/forecast/readme-generator';
import { generateReadme as generateLinkAnalysisReadme } from '../src/analysis-plugins/plugins/link-analysis/readme-generator';

// Import agent-level readme generators
import { generateReadme as generateComprehensiveReadme } from '../../db/system-agents/agents/readmes/comprehensive-checker-generator';

const READMES = {
  'fact-checker': {
    generator: generateFactCheckReadme,
    markdownOutputPath: '../../db/system-agents/agents/readmes/fact-checker.md'
  },
  'math-checker': {
    generator: generateMathReadme,
    markdownOutputPath: '../../db/system-agents/agents/readmes/math-checker.md'
  },
  'spelling-grammar': {
    generator: generateSpellingReadme,
    markdownOutputPath: '../../db/system-agents/agents/readmes/spelling-grammar.md'
  },
  'forecast-checker': {
    generator: generateForecastReadme,
    markdownOutputPath: '../../db/system-agents/agents/readmes/forecast-checker.md'
  },
  'link-checker': {
    generator: generateLinkAnalysisReadme,
    markdownOutputPath: '../../db/system-agents/agents/readmes/link-checker.md'
  },
  'comprehensive-checker': {
    generator: generateComprehensiveReadme,
    markdownOutputPath: '../../db/system-agents/agents/readmes/comprehensive-checker.md'
  }
};

// Generate markdown files and collect content
const readmeContent: Record<string, string> = {};
const failures: string[] = [];

for (const [id, config] of Object.entries(READMES)) {
  try {
    const content = config.generator();
    readmeContent[id] = content;

    // Write markdown file for human reading
    const markdownPath = path.join(__dirname, config.markdownOutputPath);
    const dir = path.dirname(markdownPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(markdownPath, content, 'utf-8');

    console.log(`✅ Generated markdown README for ${id} at ${markdownPath}`);
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    console.error(`❌ Failed to generate README for ${id}:`, error);
    failures.push(`${id}: ${errorMsg}`);
  }
}

// Generate TypeScript module for runtime access
const readmeHash = createHash('sha256').update(JSON.stringify(readmeContent)).digest('hex');

const tsOutput = `/**
 * Auto-generated plugin README content
 * Generated by scripts/generate-plugin-readmes.ts
 * DO NOT EDIT MANUALLY
 *
 * README Hash: ${readmeHash}
 */

export const pluginReadmes = ${JSON.stringify(readmeContent, null, 2)} as const;

export type PluginId = keyof typeof pluginReadmes;

export function getPluginReadme(pluginId: string): string {
  const typedPluginId = pluginId as PluginId;
  return pluginReadmes[typedPluginId] || \`# \${pluginId}\\n\\n*README content not available*\`;
}
`;

// Write TypeScript module to db package for safe imports
const tsOutputPath = path.join(__dirname, '../../db/system-agents/generated-plugin-readmes.ts');
fs.writeFileSync(tsOutputPath, tsOutput, 'utf-8');

console.log(`✅ Generated TypeScript module at ${tsOutputPath}`);
console.log(`📋 Generated ${Object.keys(readmeContent).length} plugin README(s)`);
console.log(`🔍 README hash: ${readmeHash}`);

// Report all failures and exit with error if any occurred
if (failures.length > 0) {
  console.error('\n❌ Plugin README generation completed with failures:');
  failures.forEach(failure => console.error(`  - ${failure}`));
  process.exit(1);
}
