#!/usr/bin/env tsx

/**
 * Build script to generate static README content from tool README files
 * This extracts README content at build time so it can be imported client-side
 * without file system dependencies
 */

import fs from 'fs';
import path from 'path';
import { createHash } from 'crypto';

// Import all tools from centralized registry to get tool IDs
import { allTools } from '../src/tools/all-tools';

// Read README files
const readmes: Record<string, string> = {};

for (const [id, tool] of Object.entries(allTools)) {
  const readmePath = path.join(__dirname, '..', 'src', 'tools', id, 'README.md');
  
  if (fs.existsSync(readmePath)) {
    try {
      readmes[id] = fs.readFileSync(readmePath, 'utf-8');
      console.log(`✅ Loaded README for ${id}`);
    } catch (error) {
      console.warn(`⚠️  Failed to read README for ${id}:`, error);
      readmes[id] = `# ${tool.config.name}\n\n*README content not available*`;
    }
  } else {
    console.warn(`⚠️  No README found for ${id} at ${readmePath}`);
    readmes[id] = `# ${tool.config.name}\n\n*README content not available*`;
  }
}

// Create a hash of the README content for validation
const readmeContent = JSON.stringify(readmes, null, 2);
const readmeHash = createHash('sha256').update(readmeContent).digest('hex');

// Generate TypeScript module
const output = `/**
 * Auto-generated tool README content
 * Generated by scripts/generate-tool-readmes.ts
 * DO NOT EDIT MANUALLY
 * 
 * README Hash: ${readmeHash}
 */

export const toolReadmes = ${JSON.stringify(readmes, null, 2)} as const;

export type ToolId = keyof typeof toolReadmes;

export function getToolReadme(toolId: ToolId): string {
  return toolReadmes[toolId] || \`# \${toolId}\\n\\n*README content not available*\`;
}
`;

// Write to file
const outputPath = path.join(__dirname, '..', 'src', 'tools', 'generated-readmes.ts');
fs.writeFileSync(outputPath, output);

console.log(`✅ Generated tool README content to ${outputPath}`);
console.log(`📋 Generated ${Object.keys(readmes).length} README entries`);
console.log(`🔍 README hash: ${readmeHash}`);