services:
  db:
    image: postgres:17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    name: dev-postgres-roast
