/**
 * Consolidated constants for DocumentWithEvaluations component
 * All layout, timing, and UI constants in one place
 */

// === LAYOUT CONSTANTS (in pixels) ===
export const LAYOUT = {
  // Comment column
  COMMENT_COLUMN_WIDTH: 600,
  COMMENT_PADDING: 14,
  COMMENT_MARGIN_LEFT: 5,
  COMMENT_MARGIN_RIGHT: 5,
  COMMENT_MIN_GAP: 10,
  
  // Content area
  CONTENT_SIDE_PADDING: 80,
  
  // Header
  HEADER_MAX_HEIGHT: 1000,
  CARDS_GRID_MAX_HEIGHT: 1000,
  
  // Scroll margins
  SCROLL_MARGIN_TOP: 100,
  EVAL_SECTION_OFFSET: 100,
} as const;

// === TIMING CONSTANTS (in milliseconds) ===
export const TIMING = {
  // Animations
  TRANSITION_DURATION: 300,
  TRANSITION_DURATION_SLOW: 500,
  HIGHLIGHT_TRANSITION: 150,
  
  // Delays
  SCROLL_DELAY_EXPAND: 200,
  RESIZE_DEBOUNCE_DELAY: 100,
  INITIALIZATION_DELAY: 50,
  
  // Polling
  HIGHLIGHT_CHECK_INTERVAL: 200,
  
  // User feedback
  COPY_FEEDBACK_DURATION: 2000,
  COPY_ERROR_DURATION: 3000,
} as const;

// === SCROLL THRESHOLDS (in pixels) ===
export const SCROLL = {
  THRESHOLD_TOP: 10,
  THRESHOLD_COLLAPSE: 50,
} as const;

// === Z-INDEX VALUES ===
export const Z_INDEX = {
  COMMENT: 10,
  COMMENT_HOVERED: 20,
  HEADER: 50,
} as const;

// === COLORS ===
export const COLORS = {
  COMMENT_BG_DEFAULT: "#edf2fa",
  COMMENT_BG_HOVERED: "white",
  COMMENT_BORDER_HOVERED: "#e5e7eb",
} as const;

// === COMMENT POSITIONING ===
export const COMMENT_POSITIONING = {
  // Height calculation
  BASE_HEIGHT: 20,
  AGENT_NAME_HEIGHT: 20,
  CHARS_PER_LINE: 50,
  LINE_HEIGHT: 14,
  EXPANDED_EXTRA_HEIGHT: 30,
  COMPACT_COMMENT_THRESHOLD: 100, // characters
  
  // Alignment
  HIGHLIGHT_ALIGNMENT_OFFSET: 15,
  
  // Fallback positioning
  FALLBACK_SPACING_MIN: 150,
  FALLBACK_COMMENT_BOTTOM_MARGIN: 100,
} as const;

// === TEXT PROCESSING ===
export const TEXT_PROCESSING = {
  MIN_HIGHLIGHT_LENGTH: 10,
  CONTEXT_CHARS: 50,
  MAX_COMMENT_PREVIEW_LENGTH: 250,
  MAX_PREVIEW_LINES: 2,
  TRUNCATION_SHORT_RATIO: 0.6, // For line-limited truncation
} as const;

// === LIMITS ===
export const LIMITS = {
  HIGHLIGHT_CHECK_MAX_ATTEMPTS: 20,
  MIN_UNIQUE_TAGS_RATIO: 0.5, // For highlight readiness check
} as const;

// === LEGACY EXPORTS FOR BACKWARD COMPATIBILITY ===
// TODO: Remove these after updating all imports
export const COMMENT_COLUMN_WIDTH = LAYOUT.COMMENT_COLUMN_WIDTH;
export const COMMENT_PADDING = LAYOUT.COMMENT_PADDING;
export const COMMENT_MARGIN_LEFT = LAYOUT.COMMENT_MARGIN_LEFT;
export const COMMENT_MARGIN_RIGHT = LAYOUT.COMMENT_MARGIN_RIGHT;
export const COMMENT_MIN_GAP = LAYOUT.COMMENT_MIN_GAP;

export const TRANSITION_DURATION = TIMING.TRANSITION_DURATION;
export const TRANSITION_DURATION_SLOW = TIMING.TRANSITION_DURATION_SLOW;
export const SCROLL_DELAY_EXPAND = TIMING.SCROLL_DELAY_EXPAND;
export const RESIZE_DEBOUNCE_DELAY = TIMING.RESIZE_DEBOUNCE_DELAY;
export const INITIALIZATION_DELAY = TIMING.INITIALIZATION_DELAY;
export const HIGHLIGHT_CHECK_INTERVAL = TIMING.HIGHLIGHT_CHECK_INTERVAL;
export const HIGHLIGHT_CHECK_MAX_ATTEMPTS = LIMITS.HIGHLIGHT_CHECK_MAX_ATTEMPTS;

export const SCROLL_THRESHOLD_TOP = SCROLL.THRESHOLD_TOP;
export const SCROLL_THRESHOLD_COLLAPSE = SCROLL.THRESHOLD_COLLAPSE;
export const EVAL_SECTION_OFFSET = LAYOUT.EVAL_SECTION_OFFSET;

export const Z_INDEX_COMMENT = Z_INDEX.COMMENT;
export const Z_INDEX_COMMENT_HOVERED = Z_INDEX.COMMENT_HOVERED;
export const Z_INDEX_HEADER = Z_INDEX.HEADER;

export const HEADER_MAX_HEIGHT = LAYOUT.HEADER_MAX_HEIGHT;
export const CARDS_GRID_MAX_HEIGHT = LAYOUT.CARDS_GRID_MAX_HEIGHT;

export const COMMENT_BG_DEFAULT = COLORS.COMMENT_BG_DEFAULT;
export const COMMENT_BG_HOVERED = COLORS.COMMENT_BG_HOVERED;
export const COMMENT_BORDER_HOVERED = COLORS.COMMENT_BORDER_HOVERED;