import "./globals.css";

import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Header (always visible at the top) */}
        <header className="border-b border-gray-200 px-6 py-3 bg-blue-500">
          <div className="max-w-7xl mx-auto">
            <h1 className="text-2xl font-bold text-gray-200">
              Document Analyzer
            </h1>
          </div>
        </header>

        {/* Main Content Area */}
        <main>{children}</main>
      </body>
    </html>
  );
}
