/**
 * Auto-generated tool schemas
 * Generated by scripts/generate-tool-schemas.ts
 * DO NOT EDIT MANUALLY
 * 
 * Schema Hash: 03fd6c8c36ea8ad38a61ccf1fc2e8ccca8017fecbcacc7106fea3f470eebbe59
 */

export const toolSchemas = {
  "spelling-grammar-checker": {
    "config": {
      "id": "spelling-grammar-checker",
      "name": "Spelling & Grammar Checker",
      "description": "Analyze text for spelling and grammar errors using Claude with advanced error detection",
      "version": "2.0.0",
      "category": "checker",
      "costEstimate": "~$0.01-0.02 per check",
      "path": "/tools/spelling-grammar-checker",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500000,
          "description": "The text to check for spelling and grammar errors"
        },
        "context": {
          "type": "string",
          "maxLength": 1000,
          "description": "Additional context about the text (e.g., academic paper, casual email, technical documentation)"
        },
        "maxErrors": {
          "type": "number",
          "minimum": 1,
          "maximum": 100,
          "default": 50,
          "description": "Maximum number of errors to return"
        },
        "convention": {
          "type": "string",
          "enum": [
            "US",
            "UK",
            "auto"
          ],
          "default": "auto",
          "description": "Which English convention to use"
        },
        "strictness": {
          "type": "string",
          "enum": [
            "minimal",
            "standard",
            "thorough"
          ],
          "default": "standard",
          "description": "How strict the checking should be"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "errors": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "text": {
                "type": "string",
                "description": "The EXACT incorrect text from the input"
              },
              "correction": {
                "type": "string",
                "description": "Suggested correction"
              },
              "displayCorrection": {
                "type": "string",
                "description": "XML markup for displaying correction (e.g., \"<r:replace from=\"teh\" to=\"the\"/>\")"
              },
              "type": {
                "type": "string",
                "enum": [
                  "spelling",
                  "grammar"
                ],
                "description": "Type of error"
              },
              "context": {
                "type": "string",
                "description": "Surrounding context (20-30 chars each side)"
              },
              "importance": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "Importance score (0-100)"
              },
              "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "Confidence in this error (0-100)"
              },
              "description": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "Explanation for complex cases (0 for obvious, 1-2 sentences otherwise)"
              },
              "lineNumber": {
                "type": "number",
                "description": "Approximate line number where error occurs"
              }
            },
            "required": [
              "text",
              "correction",
              "displayCorrection",
              "type",
              "importance",
              "confidence"
            ],
            "additionalProperties": false
          },
          "description": "List of errors found"
        },
        "metadata": {
          "type": "object",
          "properties": {
            "totalErrorsFound": {
              "type": "number",
              "description": "Total number of errors found (before limiting)"
            },
            "convention": {
              "type": "string",
              "enum": [
                "US",
                "UK",
                "mixed"
              ],
              "description": "Detected or applied convention"
            },
            "processingTime": {
              "type": "number",
              "description": "Processing time in milliseconds"
            }
          },
          "required": [
            "totalErrorsFound",
            "convention"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "errors"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "factual-claims-extractor": {
    "config": {
      "id": "factual-claims-extractor",
      "name": "Factual Claims Extractor",
      "description": "Extract and score verifiable factual claims from text",
      "version": "2.0.0",
      "category": "extraction",
      "costEstimate": "~$0.01-0.03 per analysis (depends on text length)",
      "path": "/tools/factual-claims-extractor",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50000,
          "description": "The text to analyze for factual claims"
        },
        "instructions": {
          "type": "string",
          "description": "Additional instructions for extraction"
        },
        "minQualityThreshold": {
          "type": "number",
          "minimum": 0,
          "maximum": 100,
          "default": 50,
          "description": "Minimum average score to include a claim"
        },
        "maxClaims": {
          "type": "number",
          "minimum": 1,
          "maximum": 100,
          "default": 50,
          "description": "Maximum number of claims to extract"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "claims": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "exactText": {
                "type": "string",
                "description": "The EXACT text as it appears in the document - used for location finding"
              },
              "claim": {
                "type": "string",
                "description": "The normalized claim text for fact-checking - can rephrase for clarity but must preserve all factual content exactly as stated"
              },
              "topic": {
                "type": "string",
                "description": "Topic/category (e.g., 'economics', 'history', 'science')"
              },
              "importanceScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "How important/central to the document"
              },
              "checkabilityScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "How easily this can be fact-checked"
              },
              "truthProbability": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "Estimated probability the fact-checker would verify as true"
              },
              "highlight": {
                "type": "object",
                "properties": {
                  "startOffset": {
                    "type": "number"
                  },
                  "endOffset": {
                    "type": "number"
                  },
                  "quotedText": {
                    "type": "string"
                  },
                  "isValid": {
                    "type": "boolean"
                  },
                  "prefix": {
                    "type": "string"
                  },
                  "error": {
                    "type": "string"
                  }
                },
                "required": [
                  "startOffset",
                  "endOffset",
                  "quotedText",
                  "isValid"
                ],
                "additionalProperties": false,
                "description": "Location information for the claim"
              }
            },
            "required": [
              "exactText",
              "claim",
              "topic",
              "importanceScore",
              "checkabilityScore",
              "truthProbability"
            ],
            "additionalProperties": false
          },
          "description": "Extracted factual claims with scores"
        },
        "summary": {
          "type": "object",
          "properties": {
            "totalFound": {
              "type": "number"
            },
            "aboveThreshold": {
              "type": "number"
            },
            "averageQuality": {
              "type": "number"
            }
          },
          "required": [
            "totalFound",
            "aboveThreshold",
            "averageQuality"
          ],
          "additionalProperties": false,
          "description": "Summary statistics"
        }
      },
      "required": [
        "claims",
        "summary"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "fact-checker": {
    "config": {
      "id": "fact-checker",
      "name": "Fact Checker",
      "description": "Verify the accuracy of specific factual claims",
      "version": "1.0.0",
      "category": "checker",
      "costEstimate": "~$0.01-0.02 per claim",
      "path": "/tools/fact-checker",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "claim": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000,
          "description": "The factual claim to verify"
        },
        "context": {
          "type": "string",
          "maxLength": 5000,
          "description": "Additional context about the claim"
        },
        "searchForEvidence": {
          "type": "boolean",
          "default": false,
          "description": "Whether to search for additional evidence"
        }
      },
      "required": [
        "claim"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "result": {
          "type": "object",
          "properties": {
            "verdict": {
              "type": "string",
              "enum": [
                "true",
                "false",
                "partially-true",
                "unverifiable",
                "outdated"
              ]
            },
            "confidence": {
              "type": "string",
              "enum": [
                "high",
                "medium",
                "low"
              ]
            },
            "explanation": {
              "type": "string"
            },
            "corrections": {
              "type": "string"
            },
            "displayCorrection": {
              "type": "string"
            },
            "criticalText": {
              "type": "string",
              "minLength": 1
            },
            "sources": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": [
                  "title",
                  "url"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "verdict",
            "confidence",
            "explanation",
            "criticalText"
          ],
          "additionalProperties": false,
          "description": "The fact-check verdict and details"
        },
        "researchNotes": {
          "type": "string",
          "description": "Additional research notes if evidence was searched"
        },
        "perplexityData": {
          "description": "Full Perplexity research results for debug"
        },
        "llmInteraction": {
          "description": "LLM interaction for monitoring"
        }
      },
      "required": [
        "result"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "math-validator-mathjs": {
    "config": {
      "id": "math-validator-mathjs",
      "name": "Math Validator (MathJS)",
      "description": "Verify mathematical statements using an agentic approach with Claude and MathJS",
      "version": "2.0.0",
      "category": "checker",
      "costEstimate": "~$0.02-0.05 per statement (uses Claude with multiple tool calls)",
      "path": "/tools/math-validator-mathjs",
      "status": "beta",
      "examples": [
        "2 + 2 = 4",
        "The binomial coefficient \"10 choose 3\" equals 120",
        "Converting 100 fahrenheit to celsius gives 37.78 degrees",
        "10% of 50 is 5",
        "sqrt(144) = 12",
        "log(1000, 10) = 3",
        "The derivative of x³ is 3x²",
        "5 km + 3000 m = 8 km",
        "The area of a circle with radius 5 is 25π",
        "sin(90 degrees) = 1"
      ]
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "statement": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000,
          "description": "A mathematical statement to verify"
        },
        "context": {
          "type": "string",
          "maxLength": 500,
          "description": "Additional context about the statement"
        }
      },
      "required": [
        "statement"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "statement": {
          "type": "string",
          "description": "The original statement that was verified"
        },
        "status": {
          "type": "string",
          "enum": [
            "verified_true",
            "verified_false",
            "verified_warning",
            "cannot_verify"
          ],
          "description": "Verification result: true (exact/good), false (wrong), warning (rough approximation), or cannot verify"
        },
        "explanation": {
          "type": "string",
          "description": "Clear explanation of why the statement is true, false, warning, or cannot be verified"
        },
        "verificationDetails": {
          "type": "object",
          "properties": {
            "mathJsExpression": {
              "type": "string",
              "description": "The MathJS expression used for verification"
            },
            "computedValue": {
              "type": "string",
              "description": "The computed value from mathematical evaluation"
            },
            "steps": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "expression": {
                    "type": "string",
                    "description": "Mathematical expression"
                  },
                  "result": {
                    "type": "string",
                    "description": "Result of the expression"
                  }
                },
                "required": [
                  "expression",
                  "result"
                ],
                "additionalProperties": false
              },
              "description": "Step-by-step calculation"
            }
          },
          "additionalProperties": false,
          "description": "Details about how the verification was performed"
        },
        "errorDetails": {
          "type": "object",
          "properties": {
            "errorType": {
              "type": "string",
              "enum": [
                "calculation",
                "logic",
                "unit",
                "notation",
                "conceptual"
              ],
              "description": "Type of mathematical error"
            },
            "severity": {
              "type": "string",
              "enum": [
                "critical",
                "major",
                "minor"
              ],
              "description": "Severity of the error"
            },
            "conciseCorrection": {
              "type": "string",
              "description": "Concise summary of the correction (e.g., \"45 → 234\", \"4x → 5x\")"
            },
            "expectedValue": {
              "type": "string",
              "description": "The expected/correct value"
            },
            "actualValue": {
              "type": "string",
              "description": "The actual/incorrect value found in the statement"
            }
          },
          "required": [
            "errorType",
            "severity",
            "conciseCorrection"
          ],
          "additionalProperties": false,
          "description": "Details about the error (only present when status is verified_false)"
        },
        "error": {
          "type": "string",
          "description": "Technical error if verification failed"
        },
        "llmInteraction": {
          "type": "object",
          "properties": {
            "model": {
              "type": "string"
            },
            "prompt": {
              "type": "string"
            },
            "response": {
              "type": "string"
            },
            "tokensUsed": {
              "type": "object",
              "properties": {
                "prompt": {
                  "type": "number"
                },
                "completion": {
                  "type": "number"
                },
                "total": {
                  "type": "number"
                }
              },
              "required": [
                "prompt",
                "completion",
                "total"
              ],
              "additionalProperties": false
            },
            "timestamp": {
              "type": "string",
              "format": "date-time"
            },
            "duration": {
              "type": "number"
            }
          },
          "required": [
            "model",
            "prompt",
            "response",
            "tokensUsed",
            "timestamp",
            "duration"
          ],
          "additionalProperties": false,
          "description": "LLM interaction for monitoring and debugging"
        }
      },
      "required": [
        "statement",
        "status",
        "explanation",
        "llmInteraction"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "math-validator-llm": {
    "config": {
      "id": "math-validator-llm",
      "name": "Math Validator (LLM)",
      "description": "Analyze text for mathematical errors including calculations, logic, units, and notation using Claude",
      "version": "1.0.0",
      "category": "checker",
      "costEstimate": "~$0.02 per check (1 Claude call with longer analysis)",
      "path": "/tools/math-validator-llm",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "statement": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000,
          "description": "A single mathematical statement to analyze (e.g., \"2 + 2 = 4\" or \"The square root of 16 is 4\")"
        },
        "context": {
          "type": "string",
          "maxLength": 500,
          "description": "Additional context about the statement"
        }
      },
      "required": [
        "statement"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "statement": {
          "type": "string",
          "description": "The original statement that was analyzed"
        },
        "status": {
          "type": "string",
          "enum": [
            "verified_true",
            "verified_false",
            "cannot_verify"
          ],
          "description": "Analysis result"
        },
        "explanation": {
          "type": "string",
          "description": "Clear explanation of why the statement is true, false, or cannot be verified"
        },
        "reasoning": {
          "type": "string",
          "description": "Detailed reasoning behind the analysis"
        },
        "errorDetails": {
          "type": "object",
          "properties": {
            "errorType": {
              "type": "string",
              "enum": [
                "calculation",
                "logic",
                "unit",
                "notation",
                "conceptual"
              ],
              "description": "Type of mathematical error"
            },
            "severity": {
              "type": "string",
              "enum": [
                "critical",
                "major",
                "minor"
              ],
              "description": "Severity of the error"
            },
            "displayCorrection": {
              "type": "string",
              "description": "XML markup for displaying correction (e.g., \"<r:replace from=\"45\" to=\"234\"/>\")"
            },
            "expectedValue": {
              "type": "string",
              "description": "The expected/correct value"
            },
            "actualValue": {
              "type": "string",
              "description": "The actual/incorrect value found in the statement"
            }
          },
          "required": [
            "errorType",
            "severity",
            "displayCorrection"
          ],
          "additionalProperties": false,
          "description": "Details about the error (only present when status is verified_false)"
        }
      },
      "required": [
        "statement",
        "status",
        "explanation",
        "reasoning"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "math-validator-hybrid": {
    "config": {
      "id": "math-validator-hybrid",
      "name": "Math Validator (Hybrid)",
      "description": "Simple wrapper: try MathJS first, then LLM as fallback",
      "version": "1.0.0",
      "category": "checker",
      "costEstimate": "~$0.01-0.03 per check (computational + optional LLM)",
      "path": "/tools/math-validator-hybrid",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "statement": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000,
          "description": "A single mathematical statement to verify (e.g., \"2 + 2 = 4\" or \"The square root of 16 is 4\")"
        },
        "context": {
          "type": "string",
          "maxLength": 500,
          "description": "Additional context about the statement"
        }
      },
      "required": [
        "statement"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "statement": {
          "type": "string",
          "description": "The original statement that was verified"
        },
        "status": {
          "type": "string",
          "enum": [
            "verified_true",
            "verified_false",
            "verified_warning",
            "cannot_verify"
          ],
          "description": "Hybrid verification result"
        },
        "explanation": {
          "type": "string",
          "description": "Clear explanation of the verification result"
        },
        "verifiedBy": {
          "type": "string",
          "enum": [
            "mathjs",
            "llm",
            "both"
          ],
          "description": "Which tool(s) provided the verification"
        },
        "mathJsResult": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": [
                "verified_true",
                "verified_false",
                "verified_warning",
                "cannot_verify"
              ],
              "description": "MathJS verification result"
            },
            "explanation": {
              "type": "string",
              "description": "MathJS explanation"
            },
            "mathJsExpression": {
              "type": "string",
              "description": "The MathJS expression used"
            },
            "computedValue": {
              "type": "string",
              "description": "Computed value from MathJS"
            },
            "steps": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "expression": {
                    "type": "string",
                    "description": "Mathematical expression"
                  },
                  "result": {
                    "type": "string",
                    "description": "Result of the expression"
                  }
                },
                "required": [
                  "expression",
                  "result"
                ],
                "additionalProperties": false
              },
              "description": "Step-by-step calculation"
            },
            "error": {
              "type": "string",
              "description": "Technical error if verification failed"
            }
          },
          "required": [
            "status",
            "explanation"
          ],
          "additionalProperties": false,
          "description": "MathJS verification details"
        },
        "llmResult": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": [
                "verified_true",
                "verified_false",
                "cannot_verify"
              ],
              "description": "LLM analysis result"
            },
            "explanation": {
              "type": "string",
              "description": "LLM explanation"
            },
            "errorType": {
              "type": "string",
              "enum": [
                "calculation",
                "logic",
                "unit",
                "notation",
                "conceptual"
              ],
              "description": "Type of error if found"
            },
            "severity": {
              "type": "string",
              "enum": [
                "critical",
                "major",
                "minor"
              ],
              "description": "Severity if error found"
            },
            "reasoning": {
              "type": "string",
              "description": "Detailed reasoning"
            }
          },
          "required": [
            "status",
            "explanation",
            "reasoning"
          ],
          "additionalProperties": false,
          "description": "LLM analysis details"
        },
        "displayCorrection": {
          "type": "string",
          "description": "XML markup for displaying correction (e.g., \"<r:replace from=\"45\" to=\"234\"/>\")"
        },
        "toolsUsed": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "mathjs",
              "llm"
            ]
          },
          "description": "Which tools were used"
        }
      },
      "required": [
        "statement",
        "status",
        "explanation",
        "verifiedBy",
        "toolsUsed"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "math-expressions-extractor": {
    "config": {
      "id": "math-expressions-extractor",
      "name": "Math Expressions Extractor",
      "description": "Extract and analyze mathematical expressions from text, including error detection and complexity assessment",
      "version": "1.0.0",
      "category": "extraction",
      "costEstimate": "~$0.02 per extraction (1 Claude call)",
      "path": "/tools/math-expressions-extractor",
      "status": "beta"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50000,
          "description": "The text to extract mathematical expressions from"
        },
        "verifyCalculations": {
          "type": "boolean",
          "default": true,
          "description": "Whether to verify calculations for errors"
        },
        "includeContext": {
          "type": "boolean",
          "default": true,
          "description": "Whether to include contextual information"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "expressions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "originalText": {
                "type": "string",
                "description": "The exact mathematical expression as it appears in the text"
              },
              "hasError": {
                "type": "boolean",
                "description": "Whether the expression contains an error"
              },
              "errorType": {
                "type": "string",
                "enum": [
                  "calculation",
                  "logic",
                  "unit",
                  "notation",
                  "conceptual"
                ],
                "description": "Type of mathematical error"
              },
              "severity": {
                "type": "string",
                "enum": [
                  "critical",
                  "major",
                  "minor"
                ],
                "description": "Severity of the error"
              },
              "errorExplanation": {
                "type": "string",
                "description": "Explanation of the error"
              },
              "correctedVersion": {
                "type": "string",
                "description": "Corrected version of the expression"
              },
              "displayCorrection": {
                "type": "string",
                "description": "XML markup for displaying the correction (e.g., \"<r:replace from=\"45\" to=\"234\"/>\")"
              },
              "complexityScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "How complex the mathematical expression is (0-100)"
              },
              "contextImportanceScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "How important this expression is to the document context (0-100)"
              },
              "errorSeverityScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "How severe the error is if present (0-100)"
              },
              "simplifiedExplanation": {
                "type": "string",
                "description": "Simplified explanation of complex expressions"
              },
              "verificationStatus": {
                "type": "string",
                "enum": [
                  "verified",
                  "unverified",
                  "unverifiable"
                ],
                "description": "Whether the calculation was verified"
              }
            },
            "required": [
              "originalText",
              "hasError",
              "complexityScore",
              "contextImportanceScore",
              "errorSeverityScore",
              "verificationStatus"
            ],
            "additionalProperties": false
          },
          "description": "List of extracted mathematical expressions"
        }
      },
      "required": [
        "expressions"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "binary-forecasting-claims-extractor": {
    "config": {
      "id": "binary-forecasting-claims-extractor",
      "name": "Binary Forecasting Claims Extractor",
      "description": "Extracts predictions and converts them to binary (YES/NO) questions. Scores on four dimensions: precision (how binary/specific), verifiability (can we check with public data), importance (centrality to argument), and robustness (how well-supported)",
      "version": "2.0.0",
      "category": "extraction",
      "costEstimate": "~$0.01-0.03 per analysis (uses Claude Sonnet)",
      "path": "/tools/binary-forecasting-claims-extractor",
      "status": "beta"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 10000,
          "description": "The text to analyze for forecasting claims"
        },
        "additionalContext": {
          "type": "string",
          "maxLength": 2000,
          "description": "Additional context about the document, company, or topic to help make predictions more specific"
        },
        "maxDetailedAnalysis": {
          "type": "number",
          "minimum": 1,
          "maximum": 10,
          "default": 3,
          "description": "Maximum number of forecasts to select for detailed analysis"
        },
        "minQualityThreshold": {
          "type": "number",
          "minimum": 0,
          "maximum": 100,
          "description": "Minimum average score (across precision, verifiability, and importance) required for a forecast to be included. Does not include robustness. Forecasts with average scores below this threshold will be filtered out."
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "forecasts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "originalText": {
                "type": "string"
              },
              "thinking": {
                "type": "string"
              },
              "precisionScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100
              },
              "verifiabilityScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100
              },
              "importanceScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100
              },
              "rewrittenPredictionText": {
                "type": "string"
              },
              "authorProbability": {
                "type": "number",
                "minimum": 0,
                "maximum": 100
              },
              "robustnessScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100
              },
              "resolutionDate": {
                "type": "string"
              },
              "minimalProbabilitySpan": {
                "type": "string"
              }
            },
            "required": [
              "originalText",
              "thinking",
              "precisionScore",
              "verifiabilityScore",
              "importanceScore",
              "rewrittenPredictionText",
              "robustnessScore"
            ],
            "additionalProperties": false
          },
          "description": "Extracted forecasts with multi-dimensional scores"
        }
      },
      "required": [
        "forecasts"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "document-chunker": {
    "config": {
      "id": "document-chunker",
      "name": "Document Chunker",
      "description": "Splits documents into semantic chunks optimized for LLM analysis. Supports multiple strategies including markdown-aware, semantic, and hybrid chunking.",
      "version": "1.0.0",
      "category": "utility",
      "costEstimate": "$0 (no LLM calls)",
      "path": "/tools/document-chunker",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500000,
          "description": "The document text to chunk"
        },
        "maxChunkSize": {
          "type": "number",
          "minimum": 100,
          "maximum": 10000,
          "default": 1500,
          "description": "Maximum size of each chunk in characters"
        },
        "minChunkSize": {
          "type": "number",
          "minimum": 50,
          "maximum": 1000,
          "default": 200,
          "description": "Minimum size of each chunk in characters"
        },
        "preserveContext": {
          "type": "boolean",
          "default": true,
          "description": "Try to preserve semantic context when chunking"
        },
        "targetWords": {
          "type": "number",
          "minimum": 50,
          "maximum": 2000,
          "default": 500,
          "description": "Target word count for recursive markdown chunking"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "chunks": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "text": {
                "type": "string"
              },
              "startOffset": {
                "type": "number"
              },
              "endOffset": {
                "type": "number"
              },
              "startLine": {
                "type": "number"
              },
              "endLine": {
                "type": "number"
              },
              "metadata": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "paragraph",
                      "section",
                      "code",
                      "list",
                      "heading",
                      "mixed"
                    ]
                  },
                  "headingContext": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "isComplete": {
                    "type": "boolean"
                  },
                  "confidence": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                  }
                },
                "required": [
                  "isComplete",
                  "confidence"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "id",
              "text",
              "startOffset",
              "endOffset",
              "startLine",
              "endLine",
              "metadata"
            ],
            "additionalProperties": false
          }
        },
        "metadata": {
          "type": "object",
          "properties": {
            "totalChunks": {
              "type": "number"
            },
            "averageChunkSize": {
              "type": "number"
            },
            "strategy": {
              "type": "string"
            },
            "warnings": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "totalChunks",
            "averageChunkSize",
            "strategy"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "chunks",
        "metadata"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "smart-text-searcher": {
    "config": {
      "id": "smart-text-searcher",
      "name": "Smart Text Searcher",
      "description": "Find the location of text within documents using multiple search strategies including exact matching, fuzzy matching, quote normalization, partial matching, and LLM fallback for paraphrased or difficult-to-find text",
      "version": "1.1.0",
      "category": "utility",
      "costEstimate": "Free (or minimal LLM cost if fallback is used)",
      "path": "/tools/smart-text-searcher",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "documentText": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100000
        },
        "searchText": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000
        },
        "context": {
          "type": "string"
        },
        "lineNumberHint": {
          "type": "number",
          "minimum": 1,
          "description": "Optional line number to help narrow search"
        },
        "options": {
          "type": "object",
          "properties": {
            "normalizeQuotes": {
              "type": "boolean"
            },
            "partialMatch": {
              "type": "boolean"
            },
            "useLLMFallback": {
              "type": "boolean"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "documentText",
        "searchText"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "searchText": {
          "type": "string"
        },
        "found": {
          "type": "boolean"
        },
        "location": {
          "type": "object",
          "properties": {
            "startOffset": {
              "type": "number"
            },
            "endOffset": {
              "type": "number"
            },
            "quotedText": {
              "type": "string"
            },
            "strategy": {
              "type": "string"
            },
            "confidence": {
              "type": "number"
            }
          },
          "required": [
            "startOffset",
            "endOffset",
            "quotedText",
            "strategy",
            "confidence"
          ],
          "additionalProperties": false
        },
        "error": {
          "type": "string"
        },
        "processingTimeMs": {
          "type": "number"
        },
        "llmUsed": {
          "type": "boolean"
        }
      },
      "required": [
        "searchText",
        "found",
        "processingTimeMs"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "language-convention-detector": {
    "config": {
      "id": "language-convention-detector",
      "name": "English Dialect Detector",
      "description": "Detect whether text uses US or UK English conventions",
      "version": "1.0.0",
      "category": "checker",
      "costEstimate": "~$0.00 (no LLM calls)",
      "path": "/tools/language-convention-detector",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500000,
          "description": "The text to analyze for language convention (multiline)"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "convention": {
          "type": "string",
          "enum": [
            "US",
            "UK"
          ],
          "description": "Dominant language convention"
        },
        "confidence": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "description": "Confidence in the detection (0-1)"
        },
        "consistency": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "description": "How consistent the document is (0-1)"
        },
        "evidence": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "word": {
                "type": "string",
                "description": "Example word found"
              },
              "convention": {
                "type": "string",
                "enum": [
                  "US",
                  "UK"
                ],
                "description": "Which convention this word belongs to"
              },
              "count": {
                "type": "number",
                "description": "Number of occurrences"
              }
            },
            "required": [
              "word",
              "convention",
              "count"
            ],
            "additionalProperties": false
          },
          "description": "Evidence supporting the detection"
        },
        "documentType": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "academic",
                "technical",
                "blog",
                "casual",
                "unknown"
              ],
              "description": "Type of document"
            },
            "confidence": {
              "type": "number",
              "minimum": 0,
              "maximum": 1,
              "description": "Confidence in document type detection"
            }
          },
          "required": [
            "type",
            "confidence"
          ],
          "additionalProperties": false,
          "description": "Detected document type"
        }
      },
      "required": [
        "convention",
        "confidence",
        "consistency",
        "evidence"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "binary-forecaster": {
    "config": {
      "id": "binary-forecaster",
      "name": "Binary Forecaster",
      "description": "Generate probability forecasts using multiple independent Claude analyses",
      "version": "1.0.0",
      "category": "research",
      "costEstimate": "~$0.05 per forecast (6 Claude calls)",
      "path": "/tools/binary-forecaster",
      "status": "experimental"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "question": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500,
          "description": "The question to forecast"
        },
        "context": {
          "type": "string",
          "maxLength": 1000,
          "description": "Additional context for the forecast"
        },
        "numForecasts": {
          "type": "number",
          "minimum": 3,
          "maximum": 20,
          "default": 6,
          "description": "Number of independent forecasts to generate"
        },
        "usePerplexity": {
          "type": "boolean",
          "default": false,
          "description": "Whether to use Perplexity for research"
        },
        "authorProbability": {
          "type": "number",
          "minimum": 0,
          "maximum": 100,
          "description": "The author's probability estimate if available"
        }
      },
      "required": [
        "question"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "probability": {
          "type": "number",
          "minimum": 0,
          "maximum": 100,
          "description": "The aggregated probability forecast (0-100)"
        },
        "description": {
          "type": "string",
          "description": "A description of the forecast and reasoning"
        },
        "consensus": {
          "type": "string",
          "enum": [
            "low",
            "medium",
            "high"
          ],
          "description": "Consensus level based on forecast agreement"
        },
        "individualForecasts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "probability": {
                "type": "number"
              },
              "reasoning": {
                "type": "string"
              }
            },
            "required": [
              "probability",
              "reasoning"
            ],
            "additionalProperties": false
          },
          "description": "Individual forecasts that were aggregated"
        },
        "statistics": {
          "type": "object",
          "properties": {
            "mean": {
              "type": "number"
            },
            "stdDev": {
              "type": "number"
            }
          },
          "required": [
            "mean",
            "stdDev"
          ],
          "additionalProperties": false,
          "description": "Statistical summary of the forecasts"
        },
        "perplexityResults": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "title",
              "url"
            ],
            "additionalProperties": false
          },
          "description": "Perplexity search results if available"
        },
        "displayCorrection": {
          "type": "string",
          "description": "XML markup for displaying probability correction"
        }
      },
      "required": [
        "probability",
        "description",
        "consensus",
        "individualForecasts",
        "statistics"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "link-validator": {
    "config": {
      "id": "link-validator",
      "name": "Link Validator",
      "description": "Extracts and validates all URLs from a text, checking their accessibility and returning detailed validation results",
      "version": "1.0.0",
      "category": "checker",
      "costEstimate": "Free (no LLM usage)",
      "path": "/tools/link-validator",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "description": "The text content to analyze for links"
        },
        "maxUrls": {
          "type": "number",
          "description": "Maximum number of URLs to validate (default: 20)"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "All URLs found in the text"
        },
        "validations": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string"
              },
              "finalUrl": {
                "type": "string"
              },
              "timestamp": {
                "type": "string",
                "format": "date-time"
              },
              "accessible": {
                "type": "boolean"
              },
              "severity": {
                "type": "string",
                "enum": [
                  "success",
                  "warning",
                  "error"
                ],
                "description": "Severity of the validation result"
              },
              "validationMethod": {
                "type": "string",
                "enum": [
                  "LessWrong GraphQL API",
                  "EA Forum GraphQL API",
                  "HTTP Request"
                ],
                "description": "Method used to validate the URL"
              },
              "error": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  },
                  "statusCode": {
                    "type": "number"
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false
              },
              "details": {
                "type": "object",
                "properties": {
                  "contentType": {
                    "type": "string"
                  },
                  "statusCode": {
                    "type": "number"
                  }
                },
                "required": [
                  "contentType",
                  "statusCode"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "url",
              "timestamp",
              "accessible",
              "severity",
              "validationMethod"
            ],
            "additionalProperties": false
          },
          "description": "Validation results for each URL"
        },
        "summary": {
          "type": "object",
          "properties": {
            "totalLinks": {
              "type": "number"
            },
            "workingLinks": {
              "type": "number"
            },
            "brokenLinks": {
              "type": "number"
            },
            "warningLinks": {
              "type": "number"
            },
            "errorBreakdown": {
              "type": "object",
              "additionalProperties": {
                "type": "number"
              }
            },
            "methodsUsed": {
              "type": "object",
              "additionalProperties": {
                "type": "number"
              },
              "description": "Count of validation methods used"
            }
          },
          "required": [
            "totalLinks",
            "workingLinks",
            "brokenLinks",
            "warningLinks",
            "errorBreakdown",
            "methodsUsed"
          ],
          "additionalProperties": false,
          "description": "Summary statistics of the link validation"
        }
      },
      "required": [
        "urls",
        "validations",
        "summary"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "perplexity-researcher": {
    "config": {
      "id": "perplexity-researcher",
      "name": "Perplexity Researcher",
      "description": "Web-enhanced research using Perplexity Sonar models via OpenRouter",
      "version": "1.0.0",
      "category": "research",
      "costEstimate": "~$0.001-0.005 per query (via OpenRouter)",
      "path": "/tools/perplexity-researcher",
      "status": "stable"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000,
          "description": "The research query or question"
        },
        "focusArea": {
          "type": "string",
          "enum": [
            "general",
            "academic",
            "news",
            "technical",
            "market"
          ],
          "default": "general",
          "description": "The focus area for research"
        },
        "maxSources": {
          "type": "number",
          "minimum": 1,
          "maximum": 10,
          "default": 5,
          "description": "Maximum number of sources to include"
        },
        "includeForecastingContext": {
          "type": "boolean",
          "default": false,
          "description": "Whether to include specific forecasting context"
        }
      },
      "required": [
        "query"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "summary": {
          "type": "string",
          "description": "Comprehensive summary of the research"
        },
        "sources": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "snippet": {
                "type": "string"
              }
            },
            "required": [
              "title",
              "url",
              "snippet"
            ],
            "additionalProperties": false
          },
          "description": "Sources found during research"
        },
        "keyFindings": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Key findings as bullet points"
        },
        "forecastingContext": {
          "type": "string",
          "description": "Context specifically for forecasting"
        }
      },
      "required": [
        "summary",
        "sources",
        "keyFindings"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "claim-evaluator": {
    "config": {
      "id": "claim-evaluator",
      "name": "Claim Evaluator",
      "description": "Evaluate claims by polling multiple LLM models in parallel (Claude, GPT, Grok) via OpenRouter. Each model provides an agreement score (0-100), brief reasoning, and response time in milliseconds.",
      "version": "1.0.0",
      "category": "research",
      "costEstimate": "~$0.01-0.05 per claim (4+ model calls via OpenRouter)",
      "path": "/tools/claim-evaluator",
      "status": "experimental"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "claim": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000,
          "description": "The claim to evaluate"
        },
        "context": {
          "type": "string",
          "maxLength": 30000,
          "description": "Additional context about the claim (when/where made, background, domain knowledge, constraints)"
        },
        "models": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "anthropic/claude-sonnet-4.5",
              "anthropic/claude-sonnet-4",
              "google/gemini-2.5-pro",
              "google/gemini-2.5-flash",
              "openai/gpt-5",
              "openai/gpt-5-mini",
              "deepseek/deepseek-chat-v3.1",
              "x-ai/grok-4",
              "anthropic/claude-3.5-sonnet",
              "anthropic/claude-3-7-sonnet-20250219",
              "openai/gpt-4-turbo",
              "openai/gpt-4.1",
              "openai/gpt-4.1-mini-2025-04-14",
              "x-ai/grok-beta",
              "anthropic/claude-3-haiku",
              "anthropic/claude-haiku-4.5",
              "openai/gpt-3.5-turbo",
              "deepseek/deepseek-chat",
              "anthropic/claude-3-opus",
              "anthropic/claude-4-sonnet-20250522",
              "openai/gpt-4",
              "google/gemini-pro",
              "meta-llama/llama-3-70b-instruct"
            ]
          },
          "description": "List of OpenRouter model IDs to use (defaults to top reasoning models)"
        },
        "runs": {
          "type": "integer",
          "minimum": 1,
          "maximum": 5,
          "description": "Number of times to run each model independently (1-5, default 1)"
        },
        "explanationLength": {
          "type": "integer",
          "minimum": 3,
          "maximum": 200,
          "description": "Explanation Length (Max Words): Maximum words per explanation (3-200, default 50)"
        },
        "temperature": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "description": "Temperature for model responses - lower is more consistent, higher is more varied (0.0-1.0, default 0.7). Automatically scaled per provider."
        },
        "promptTemplate": {
          "type": "string",
          "maxLength": 50000,
          "description": "Custom prompt template using {{VARIABLE}} syntax. Available variables: {{CLAIM}}, {{CONTEXT}}, {{EXPLANATION_LENGTH}}, {{RUN_NOTE}}, {{CONTEXT_SECTION}}. If not provided, uses the default template."
        }
      },
      "required": [
        "claim"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "evaluations": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "model": {
                "type": "string",
                "description": "Model identifier"
              },
              "provider": {
                "type": "string",
                "description": "Provider name (e.g., 'anthropic', 'openai')"
              },
              "hasError": {
                "type": "boolean",
                "description": "True if evaluation failed, false if successful"
              },
              "responseTimeMs": {
                "type": "number",
                "description": "Time taken for LLM to respond in milliseconds"
              },
              "rawResponse": {
                "type": "string",
                "description": "Full raw response from model (or error response)"
              },
              "thinkingText": {
                "type": "string",
                "description": "Extended thinking/reasoning (for o1/o3 models)"
              },
              "tokenUsage": {
                "type": "object",
                "properties": {
                  "promptTokens": {
                    "type": "number"
                  },
                  "completionTokens": {
                    "type": "number"
                  },
                  "totalTokens": {
                    "type": "number"
                  }
                },
                "required": [
                  "promptTokens",
                  "completionTokens",
                  "totalTokens"
                ],
                "additionalProperties": false,
                "description": "Token usage statistics"
              },
              "successfulResponse": {
                "type": "object",
                "properties": {
                  "agreement": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 100,
                    "description": "Agreement score 0-100"
                  },
                  "confidence": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 100,
                    "description": "Confidence score 0-100"
                  },
                  "reasoning": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000,
                    "description": "Brief reasoning (configurable by explanationLength in words)"
                  }
                },
                "required": [
                  "agreement",
                  "confidence",
                  "reasoning"
                ],
                "additionalProperties": false,
                "description": "Present when hasError is false"
              },
              "failedResponse": {
                "type": "object",
                "properties": {
                  "error": {
                    "type": "string",
                    "description": "Error message"
                  },
                  "refusalReason": {
                    "type": "string",
                    "enum": [
                      "Safety",
                      "Policy",
                      "MissingData",
                      "Unclear",
                      "Error"
                    ],
                    "description": "Categorized refusal/error reason"
                  },
                  "errorDetails": {
                    "type": "string",
                    "description": "Additional error context"
                  }
                },
                "required": [
                  "error",
                  "refusalReason"
                ],
                "additionalProperties": false,
                "description": "Present when hasError is true"
              }
            },
            "required": [
              "model",
              "provider",
              "hasError"
            ],
            "additionalProperties": false
          },
          "description": "Array of all model evaluations (both successful and failed)"
        },
        "summary": {
          "type": "object",
          "properties": {
            "mean": {
              "type": "number",
              "description": "Mean agreement score across all successful evaluations"
            }
          },
          "required": [
            "mean"
          ],
          "additionalProperties": false,
          "description": "Summary statistics of evaluations"
        }
      },
      "required": [
        "evaluations"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "fallacy-review": {
    "config": {
      "id": "fallacy-review",
      "name": "Fallacy Review",
      "description": "Reviews and filters fallacy check comments, removing redundant issues and generating comprehensive document summaries",
      "version": "1.0.0",
      "category": "utility",
      "path": "/tools/fallacy-review",
      "status": "beta"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "documentText": {
          "type": "string",
          "minLength": 1
        },
        "comments": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "index": {
                "type": "number"
              },
              "header": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "level": {
                "type": "string",
                "enum": [
                  "error",
                  "warning",
                  "nitpick",
                  "info",
                  "success",
                  "debug"
                ]
              },
              "importance": {
                "type": "number"
              },
              "quotedText": {
                "type": "string"
              }
            },
            "required": [
              "index",
              "header",
              "description",
              "level",
              "quotedText"
            ],
            "additionalProperties": false
          },
          "minItems": 0
        }
      },
      "required": [
        "documentText",
        "comments"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "commentIndicesToKeep": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "documentSummary": {
          "type": "string",
          "minLength": 200,
          "maxLength": 800
        },
        "oneLineSummary": {
          "type": "string",
          "minLength": 20,
          "maxLength": 200
        }
      },
      "required": [
        "commentIndicesToKeep",
        "documentSummary",
        "oneLineSummary"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  },
  "fallacy-extractor": {
    "config": {
      "id": "fallacy-extractor",
      "name": "Fallacy Extractor",
      "description": "Extract and score potential misinformation, missing context, deceptive wording, and logical fallacies from text",
      "version": "1.0.0",
      "category": "extraction",
      "costEstimate": "~$0.01-0.03 per analysis (uses Claude Sonnet)",
      "path": "/tools/fallacy-extractor",
      "status": "beta"
    },
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50000
        },
        "documentText": {
          "type": "string"
        },
        "chunkStartOffset": {
          "type": "number",
          "minimum": 0
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "outputSchema": {
      "type": "object",
      "properties": {
        "issues": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "exactText": {
                "type": "string",
                "description": "The EXACT text from the document that has the epistemic issue"
              },
              "issueType": {
                "type": "string",
                "enum": [
                  "misinformation",
                  "missing-context",
                  "deceptive-wording",
                  "logical-fallacy",
                  "verified-accurate"
                ],
                "description": "Type of epistemic issue identified"
              },
              "fallacyType": {
                "type": "string",
                "enum": [
                  "ad-hominem",
                  "straw-man",
                  "false-dilemma",
                  "slippery-slope",
                  "appeal-to-authority",
                  "appeal-to-emotion",
                  "appeal-to-nature",
                  "hasty-generalization",
                  "survivorship-bias",
                  "selection-bias",
                  "cherry-picking",
                  "circular-reasoning",
                  "equivocation",
                  "non-sequitur",
                  "other"
                ],
                "description": "Specific fallacy type (only for logical-fallacy issues)"
              },
              "severityScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "Severity score from 0-100 (higher = more severe)"
              },
              "confidenceScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "Confidence score from 0-100 (higher = more confident this is the fallacy)"
              },
              "reasoning": {
                "type": "string",
                "description": "Detailed reasoning for why this is an issue"
              },
              "importanceScore": {
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "description": "How important to address (0-100)"
              },
              "approximateLineNumber": {
                "type": "number",
                "description": "Approximate line number where this text appears (helps with faster location finding)"
              }
            },
            "required": [
              "exactText",
              "issueType",
              "severityScore",
              "confidenceScore",
              "reasoning",
              "importanceScore"
            ],
            "additionalProperties": false
          }
        },
        "totalIssuesFound": {
          "type": "number"
        },
        "wasComplete": {
          "type": "boolean"
        }
      },
      "required": [
        "issues",
        "totalIssuesFound",
        "wasComplete"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  }
} as const;

export type ToolId = keyof typeof toolSchemas;

export function getToolSchema(toolId: ToolId) {
  return toolSchemas[toolId];
}
