name: Docker Build and Push

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Prevent hanging builds
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false # Don't stop other builds if one fails
      matrix:
        include:
          - dockerfile: Dockerfile
            suffix: ""
            name: "main"
          - dockerfile: Dockerfile.worker
            suffix: "-worker"
            name: "worker"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image (${{ matrix.name }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=${{ matrix.name }}
            type=gha,scope=shared
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}

      - name: Copy runtime test script to container
        if: github.event_name == 'pull_request'
        run: |
          # Copy the runtime test script for use in Docker
          docker create --name test-container ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }}
          docker cp dev/scripts/docker-runtime-test.js test-container:/tmp/runtime-test.js
          docker rm test-container

      - name: Test Docker image - Basic functionality
        if: github.event_name == 'pull_request'
        run: |
          echo "Testing basic Docker image functionality..."
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }} node -e "console.log('Basic Node.js test passed')"
          
      - name: Test Docker image - Package availability
        if: github.event_name == 'pull_request'
        run: |
          echo "Testing package availability for ${{ matrix.name }} image..."
          
          if [ "${{ matrix.suffix }}" = "-worker" ]; then
            # Worker image tests - has full workspace
            docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }} sh -c "
              echo 'Checking pnpm...' && pnpm --version && 
              echo 'Checking workspace packages...' &&
              test -d /app/internal-packages/db/dist || (echo '@roast/db not built' && exit 1) &&
              test -d /app/internal-packages/domain/dist || (echo '@roast/domain not built' && exit 1) &&
              test -d /app/internal-packages/ai/dist || (echo '@roast/ai not built' && exit 1) &&
              test -d /app/node_modules/.prisma/client || (echo 'Prisma client not generated' && exit 1) &&
              echo 'All workspace packages available!'
            "
          else
            # Main image tests - standalone Next.js app
            docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }} sh -c "
              echo 'Checking application structure...' &&
              test -f /app/apps/web/server.js || (echo 'server.js not found' && exit 1) &&
              test -d /app/apps/web/.next/static || (echo 'Static assets not found' && exit 1) &&
              test -d /app/prisma || (echo 'Prisma schema not found' && exit 1) &&
              echo 'Main application structure OK!'
            "
          fi
          
      - name: Test Docker image - Runtime validation
        if: github.event_name == 'pull_request'
        run: |
          echo "Running runtime validation for ${{ matrix.name }} image..."
          
          if [ "${{ matrix.suffix }}" = "-worker" ]; then
            # Worker image - test that it can access workspace packages
            docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }} node -e "
              const fs = require('fs');
              const packages = ['@roast/db', '@roast/domain', '@roast/ai'];
              for (const pkg of packages) {
                const pkgJsonPath = \`/app/node_modules/\${pkg}/package.json\`;
                if (!fs.existsSync(pkgJsonPath)) {
                  console.error(\`Package \${pkg} not properly linked\`);
                  process.exit(1);
                }
              }
              console.log('All workspace packages properly linked');
            "
          else
            # Main image - test that the Next.js server can initialize
            docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }} timeout 10 node /app/apps/web/server.js > /dev/null 2>&1 || [ \$? -eq 124 ] && echo "Standalone server can initialize"
          fi
            
      - name: Test Worker-specific functionality
        if: github.event_name == 'pull_request' && matrix.suffix == '-worker'
        run: |
          echo "Testing worker-specific functionality..."
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:pr-${{ github.event.number }} sh -c "
            echo 'Checking tsx availability...' &&
            pnpm tsx --version &&
            echo 'Checking job processor script...' &&
            test -f /app/apps/web/scripts/adaptive-job-processor.ts || (echo 'Job processor script missing' && exit 1) &&
            echo 'Worker functionality verified!'
          "

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name != 'pull_request'
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - suffix: ""
            name: "main"
          - suffix: "-worker" 
            name: "worker"

    steps:
      - name: Run Trivy vulnerability scanner (${{ matrix.name }})
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.suffix }}:${{ github.ref_name }}
          format: 'sarif'
          output: 'trivy-results-${{ matrix.name }}.sarif'

      - name: Upload Trivy scan results to GitHub Security tab (${{ matrix.name }})
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-${{ matrix.name }}.sarif'